image: docker:git

services:
  - docker:dind

stages:
  - build
  - test

variables:
  # Docker registry config
  DOCKER_REGISTRY_URL: registry.gitlab.com
  DOCKER_REGISTRY_USER: gitlab-ci-token
  PROJECT_PATH: ${DOCKER_REGISTRY_URL}/johnytiago/${CI_PROJECT_NAME}

# Build the base image and store it as an artifact
#  - PROJECT_PATH: docker image repository path
build:image:
  stage: build
  image: docker:latest
  tags:
    - docker
  script:
    - docker login -u ${DOCKER_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${DOCKER_REGISTRY_URL}
    - docker build --rm -t ${PROJECT_PATH}:${CI_COMMIT_SHA} .
    - docker tag ${PROJECT_PATH}:${CI_COMMIT_SHA} ${PROJECT_PATH}:latest
    - docker push ${PROJECT_PATH}:${CI_COMMIT_SHA}
    - docker push ${PROJECT_PATH}:latest

# Build the test image based on the base prod image and run the tests
#  - PROJECT_PATH: docker image repository path
test:node:core:
  stage: test
  image: docker:latest
  dependencies:
    - build:image
  tags:
    - docker
  script:
    - docker run ${PROJECT_PATH}:${CI_COMMIT_SHA} npm run test:node:core

test:startrail:
  stage: test
  image: docker:latest
  dependencies:
    - build:image
  tags:
    - docker
  script:
    - docker run ${PROJECT_PATH}:${CI_COMMIT_SHA} npm run test:node:core:startrail
